"""mncs-rights-provenance: rights & provenance subsystem for the MNCS family.

This package is the reference implementation of the MNCS Rights & Provenance
v0.2 contracts:

- creation, reading, and manipulation of rights manifests and evidence records;
- canonical (RFC 8785-compatible) serialization and SHA-256 content identities;
- structural validation of manifests, evidence records, and policy profiles;
- release-policy gate evaluation producing structured outcomes;
- SPDX 2.3 import/export mapping.

The normative *policy decision semantics* live in the MNCS-language module
``mncs.rights.policy`` in this repository's ``language/`` directory. The Python
implementation here mirrors those semantics and is tested against golden
vectors generated by executing the MNCS-language core across compiler backends.
"""

from .canonical import canonical_bytes, sha256_hex
from .model import (
    Artifact,
    EvidenceRef,
    GraphEdge,
    GraphNode,
    Manifest,
    Participant,
    Rights,
    Review,
    Source,
    Attestation,
)
from .manifest import (
    manifest_from_dict,
    manifest_to_dict,
    compute_manifest_identity,
    load_manifest_file,
    SCHEMA_VERSION,
)
from .evidence import (
    EvidenceRecord,
    evidence_record_from_dict,
    evidence_record_to_dict,
    compute_evidence_digest,
)
from .validation import validate_manifest_structure
from .policy import (
    DEFAULT_PROFILE_ID,
    evaluate_policy,
    GateResult,
    PolicyOutcome,
    profile_from_dict,
)
from .graph import check_graph_integrity

__version__ = "0.2.0"

__all__ = [
    "Artifact",
    "Attestation",
    "DEFAULT_PROFILE_ID",
    "EvidenceRef",
    "EvidenceRecord",
    "GateResult",
    "GraphEdge",
    "GraphNode",
    "Manifest",
    "Participant",
    "PolicyOutcome",
    "Rights",
    "Review",
    "SCHEMA_VERSION",
    "Source",
    "canonical_bytes",
    "check_graph_integrity",
    "compute_evidence_digest",
    "compute_manifest_identity",
    "evaluate_policy",
    "evidence_record_from_dict",
    "evidence_record_to_dict",
    "load_manifest_file",
    "manifest_from_dict",
    "manifest_to_dict",
    "profile_from_dict",
    "sha256_hex",
    "validate_manifest_structure",
]
