"""mncs-rights-provenance: rights & provenance subsystem for the MNCS family.

This package is the reference implementation of the MNCS Rights & Provenance
v0.2 contracts:

- creation, reading, and manipulation of rights manifests and evidence records;
- canonical (RFC 8785-compatible) serialization and SHA-256 content identities;
- structural validation of manifests, evidence records, and policy profiles;
- release-policy gate evaluation producing structured outcomes;
- SPDX 2.3 import/export mapping.

The normative *policy decision semantics* live in the MNCS-language module
``mncs.rights.policy`` in this repository's ``language/`` directory. The Python
implementation here mirrors those semantics and is tested against golden
vectors generated by executing the MNCS-language core across compiler backends.
"""

from .authority import (
    ACTOR_CLASSES,
    ACTOR_TYPES,
    AUTHORITY_SCOPES,
    ActorRef,
    AuthorityClaim,
    authority_claim_from_dict,
    authority_verdict,
)
from .canonical import canonical_bytes, sha256_hex
from .evidence import (
    EvidenceRecord,
    compute_evidence_digest,
    evidence_record_from_dict,
    evidence_record_to_dict,
)
from .graph import check_graph_integrity
from .lineage import (
    LineageRecord,
    compute_lineage_digest,
    lineage_record_from_dict,
    lineage_verdict,
    migrate_manifest_02_to_03,
    seal_lineage_record,
    verify_lineage_digest,
)
from .manifest import (
    BASE_SCHEMA_VERSION,
    SCHEMA_VERSION,
    SUPPORTED_MANIFEST_VERSIONS,
    compute_manifest_identity,
    load_manifest_file,
    manifest_from_dict,
    manifest_to_dict,
)
from .model import (
    Artifact,
    Attestation,
    EvidenceRef,
    GraphEdge,
    GraphNode,
    Manifest,
    Participant,
    Review,
    Rights,
    Source,
)
from .policy import (
    DEFAULT_PROFILE_ID,
    GateResult,
    PolicyOutcome,
    evaluate_policy,
    profile_from_dict,
)
from .promotion import (
    PromotionDimension,
    PromotionInputs,
    combine_verdict,
    promotion_combined,
    promotion_inputs_from_dict,
    promotion_report,
)
from .validation import (
    validate_lineage_structure,
    validate_manifest_structure,
)

__version__ = "0.3.0"

__all__ = [
    "ACTOR_CLASSES",
    "ACTOR_TYPES",
    "AUTHORITY_SCOPES",
    "BASE_SCHEMA_VERSION",
    "DEFAULT_PROFILE_ID",
    "SCHEMA_VERSION",
    "SUPPORTED_MANIFEST_VERSIONS",
    "ActorRef",
    "Artifact",
    "Attestation",
    "AuthorityClaim",
    "EvidenceRecord",
    "EvidenceRef",
    "GateResult",
    "GraphEdge",
    "GraphNode",
    "LineageRecord",
    "Manifest",
    "Participant",
    "PolicyOutcome",
    "PromotionDimension",
    "PromotionInputs",
    "Review",
    "Rights",
    "Source",
    "authority_claim_from_dict",
    "authority_verdict",
    "canonical_bytes",
    "check_graph_integrity",
    "combine_verdict",
    "compute_evidence_digest",
    "compute_lineage_digest",
    "compute_manifest_identity",
    "evaluate_policy",
    "evidence_record_from_dict",
    "evidence_record_to_dict",
    "lineage_record_from_dict",
    "lineage_verdict",
    "load_manifest_file",
    "manifest_from_dict",
    "manifest_to_dict",
    "migrate_manifest_02_to_03",
    "profile_from_dict",
    "promotion_combined",
    "promotion_inputs_from_dict",
    "promotion_report",
    "seal_lineage_record",
    "sha256_hex",
    "validate_lineage_structure",
    "validate_manifest_structure",
    "verify_lineage_digest",
]
